# Generated by Django 4.2 on 2023-05-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_age', models.IntegerField()),
                ('emp_id', models.IntegerField()),
                ('employee_salary', models.IntegerField()),
            ],
        ),
    ]
