# Generated by Django 3.1.5 on 2023-05-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='book/pdf/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book/cover/')),
            ],
        ),
    ]
